# Compiling doldecomp/melee's decompiled C for a host target.
#
# Three accommodations stand between that source and a host compiler, and they
# are the whole of it:
#
#   1. upstream's Runtime/platform.h declares ssize_t as int, which collides
#      with the host libc wherever one is provided.  A generated header
#      shadows it on the include path, renames the typedef for the duration of
#      the real header, and keeps the host's;
#   2. Aurora's Dolphin headers give the integer types their host-correct
#      widths but omit a few SDK spellings.  include/melee/port/dolphin_compat.h
#      supplies them and is force-included ahead of every translation unit;
#   3. the structure-layout assertions verify the match against the original
#      GameCube binary and are meaningless once pointers are 64 bits, so
#      MUST_MATCH and LINT stay undefined.
#
# See docs/UPSTREAM_NATIVE_SPIKE.md for what was measured, and docs/PLAN.md
# for where this fits.

# Resolved while this file is being read, when CMAKE_CURRENT_LIST_DIR is this
# directory rather than whichever CMakeLists.txt calls the functions below.
set(MELEE_REPOSITORY_ROOT ${CMAKE_CURRENT_LIST_DIR}/..)
set(MELEE_UPSTREAM_ROOT ${MELEE_REPOSITORY_ROOT}/extern/melee)
set(MELEE_UPSTREAM_SOURCE ${MELEE_UPSTREAM_ROOT}/src)

# TRUE when the submodule has been checked out.
function(melee_upstream_available result)
    if (EXISTS ${MELEE_UPSTREAM_SOURCE}/Runtime/platform.h)
        set(${result} TRUE PARENT_SCOPE)
    else ()
        set(${result} FALSE PARENT_SCOPE)
    endif ()
endfunction()

# Generates the platform.h shadow and returns the directory holding it.
function(melee_upstream_shim result)
    set(shim ${CMAKE_BINARY_DIR}/melee_upstream_shim)
    file(MAKE_DIRECTORY ${shim}/Runtime)
    file(WRITE ${shim}/Runtime/platform.h
"#ifndef MELEE_UPSTREAM_PLATFORM_SHIM_H
#define MELEE_UPSTREAM_PLATFORM_SHIM_H

/* Generated by cmake/MeleeUpstream.cmake; shadows upstream's header. */

#include <stddef.h>
#include <stdint.h>

#if defined(__unix__) || defined(__APPLE__)
#include <sys/types.h>
#define MELEE_HOST_DECLARES_SSIZE_T 1
#endif

/* Upstream declares ssize_t as int.  Where the host libc already declares it,
   rename upstream's for the duration of that header and keep the host's. */
#ifdef MELEE_HOST_DECLARES_SSIZE_T
#define ssize_t melee_upstream_ssize_t
#endif

#include \"${MELEE_UPSTREAM_SOURCE}/Runtime/platform.h\"

#ifdef MELEE_HOST_DECLARES_SSIZE_T
#undef ssize_t
#endif

/* The real header removes the SDK boolean spellings, which Aurora's own
   Dolphin headers still declare with.  Put them back behind it. */
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif

#endif /* MELEE_UPSTREAM_PLATFORM_SHIM_H */
")
    set(${result} ${shim} PARENT_SCOPE)
endfunction()

# Puts the include paths, definitions and prelude an upstream source needs on
# `target`.  The prelude is force-included, so upstream sources compile
# unmodified.
function(melee_upstream_configure target)
    melee_upstream_shim(shim)
    set(repository ${MELEE_REPOSITORY_ROOT})
    set(prelude ${repository}/include/melee/port/dolphin_compat.h)

    target_include_directories(${target} PRIVATE
            # The shadow has to precede upstream's own src on the path.
            ${shim}
            ${repository}/include
            ${repository}/extern/aurora/include
            ${repository}/extern/aurora/include/dolphin
            ${MELEE_UPSTREAM_SOURCE}
            ${MELEE_UPSTREAM_SOURCE}/sysdolphin/baselib
            # Last: only reached for headers Aurora does not carry at all.
            ${MELEE_UPSTREAM_ROOT}/extern/dolphin/include
    )
    target_compile_definitions(${target} PRIVATE
            TARGET_PC NDEBUG=1 VERSION_NTSC102)

    # Upstream's C is force-fed the prelude; the port's own C++ includes it
    # deliberately, through tests/hsd/hsd_api.hpp.
    if (MSVC)
        target_compile_options(${target} PRIVATE
                $<$<COMPILE_LANGUAGE:C>:/FI${prelude}>
                # Upstream is written for a compiler that accepts these.
                $<$<COMPILE_LANGUAGE:C>:/wd4013>
                $<$<COMPILE_LANGUAGE:C>:/wd4133>
                $<$<COMPILE_LANGUAGE:C>:/wd4244>
                $<$<COMPILE_LANGUAGE:C>:/wd4267>)
    else ()
        target_compile_options(${target} PRIVATE
                $<$<COMPILE_LANGUAGE:C>:-include$<SEMICOLON>${prelude}>
                $<$<COMPILE_LANGUAGE:C>:-Wno-incompatible-function-pointer-types>
                $<$<COMPILE_LANGUAGE:C>:-Wno-implicit-function-declaration>)
    endif ()
endfunction()

# Absolute paths for upstream translation units named as `sysdolphin/baselib/x`.
function(melee_upstream_sources result)
    set(paths "")
    foreach (unit ${ARGN})
        list(APPEND paths ${MELEE_UPSTREAM_SOURCE}/${unit}.c)
    endforeach ()
    set(${result} ${paths} PARENT_SCOPE)
endfunction()
